## Naive Bayes

In [1]:
import pandas as pd
import pickle

In [2]:
data = pickle.load(open('data/df_clean_izq.pkl','rb'))

In [3]:
data.sample(5)

topics                          date              flyer  \
11  inflation  \nMiércoles 30 de septiembre      COSTO DE VIDA   
46   exchange     \nMiércoles 21 de octubre  TENSIÓN CAMBIARIA   
50   exchange        \nViernes 9 de octubre     TIPO DE CAMBIO   
5   inflation      \nMartes 17 de noviembre      INFORME INDEC   
57   exchange         \nViernes 24 de julio     TIPO DE CAMBIO   

                                                 lead  \
11  La cifra surge del Índice de salarios de julio...   
46  Este miércoles anota una nueva jornada de suba...   
50  La divisa paralela se vende a $ 167 y acumula ...   
5   El Indec informó que la Canasta Básica Total, ...   
57  Las restricciones para comprar el billete ofic...   

                                             headline  \
11  Los salarios perdieron casi 5 % contra la infl...   
46  Los especuladores no dan tregua: el dólar fina...   
50         Nuevo récord: el dólar blue vuelve a subir   
5   Imposible llegar a fin de mes: el costo de vid...   
57  El dólar blue saltó a $ 140 y marcó un nuevo r...   

                                                 body  \
11  El Indec publicó este miércoles el Indice de s...   
46  La cotización de la divisa norteamericana sigu...   
50  La tensión cambiaria no se detiene. El dólar b...   
5   El Indec informó este martes que la Canasta Bá...   
57  El dólar blue aumentó casi $ 10 en una semana....   

                                                  url  
11  https://www.laizquierdadiario.com/Economia/Los...  
46  https://www.laizquierdadiario.com/Economia/Los...  
50  https://www.laizquierdadiario.com/Economia/Nue...  
5   https://www.laizquierdadiario.com/Economia/Imp...  
57  https://www.laizquierdadiario.com/Economia/El-...

In [4]:
df_inflation = data.loc[data.topics == 'inflation']
df_inflation.shape

(34, 7)

In [5]:
df_exchange = data.loc[data.topics == 'exchange']
df_exchange.shape

(26, 7)

In [6]:
corpus = list(df_inflation.body.values) + list(df_exchange.body.values)
len(corpus)

60

In [7]:
target = list(df_inflation.topics.values) + list(df_exchange.topics.values)

In [8]:
data = pd.DataFrame([corpus, target]).transpose()
data

0          1
0   Se trata del mismo aumento que aplicó Massalin...  inflation
1   La petrolera Raizen, dueña de la marca Shell, ...  inflation
2   Los precios de los combustibles comercializado...  inflation
3   ¿Cuántos días te dura el salario del mes? Segu...  inflation
4   El Indec informó este jueves que el Índice de ...  inflation
5   El Indec informó este martes que la Canasta Bá...  inflation
6   Este jueves la Dirección de Estadísticas e Inv...  inflation
7   La suba de precios no se detiene. Según anunci...  inflation
8   Este miércoles el Indec publicó el índice de p...  inflation
9   El Indec publicó que la canasta de pobreza fue...  inflation
10  La Federación Argentina de la Industria del Pa...  inflation
11  El Indec publicó este miércoles el Indice de s...  inflation
12  Directivos de cámaras de supermercados denunci...  inflation
13  El último año de gobierno de Mauricio Macri el...  inflation
14  YPF aumenta los combustibles un 3,5 % en prome...  inflation
15  La Canasta Básica Total (CBT) registró en agos...  inflation
16  En una entrevista en Tiempo Argentino el empre...  inflation
17  Este jueves, la Dirección de Estadísticas e In...  inflation
18  El Indec publicó este martes que los precios m...  inflation
19  Este miércoles, la Dirección de Estadísticas d...  inflation
20  La crisis económica se sigue profundizando, el...  inflation
21  El INDEC presentó este miércoles los datos de ...  inflation
22  El informe de Precios al Consumidor elaborado ...  inflation
23  En abril, el segundo mes de la cuarentena obli...  inflation
24  El Indec publicó que la inflación de abril fue...  inflation
25  Durante la mañana de este martes fue tendencia...  inflation
26  En el primer mes de la cuarentena obligatoria ...  inflation
27  La inflación se aceleró en marzo al 3,3 %, acu...  inflation
28  En medio de la cuarentena hacer las compras pa...  inflation
29  En lo que va de 2020 las acciones de YPF perdi...  inflation
30  La inflación de febrero fue del 2 %, según inf...  inflation
31  El índice de precios mayoristas aumentó 1,5 % ...  inflation
32  En el inicio del año la inflación según la Dir...  inflation
33  Este jueves el Indec dará a conocer la inflaci...  inflation
34  La Comisión Nacional de Valores (CNV) a través...   exchange
35  El día después de la votación del Presupuesto ...   exchange
36  El dólar blue vuelve a aumentar este viernes. ...   exchange
37  El dólar blue tuvo un incremento de cinco peso...   exchange
38  En medio de las reuniones con la delegación de...   exchange
39  El dólar blue volvió a bajar este martes y se ...   exchange
40  El Gobierno de Alberto Fernández pagó esta sem...   exchange
41  La falta de dólares es un “problema estructura...   exchange
42  El dólar blue descendió este jueves a $ 175, m...   exchange
43  Este martes el Gobierno hará una emisión de de...   exchange
44  La semana empezó con una fuerte volatilidad en...   exchange
45  El dólar blue se vende a $ 195 y alcanza un nu...   exchange
46  La cotización de la divisa norteamericana sigu...   exchange
47  Luego de las medidas anunciadas por el Ministe...   exchange
48  Este lunes el ministerio de Economía anunció n...   exchange
49  La tensión en el mercado de cambios no cede, r...   exchange
50  La tensión cambiaria no se detiene. El dólar b...   exchange
51  El dólar blue alcanzó los $ 158 para la venta,...   exchange
52  El dólar en el mercado informal aumentó $ 2 pa...   exchange
53  Las medidas anunciadas por el Banco Central y ...   exchange
54  El dólar blue cayó $ 1 este viernes y cerró en...   exchange
55  Tras las nuevas medidas dispuestas por el Banc...   exchange
56  Tras la euforia en los “mercados” por el acuer...   exchange
57  El dólar blue aumentó casi $ 10 en una semana....   exchange
58  El dólar blue alcanzó los $ 138, el “contado c...   exchange
59  El dólar paralelo tuvo otra jornada de suba. E...   exchange

### Train - Test Split

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
train,test,y_train,y_test = train_test_split(data.iloc[:,0], data.iloc[:,1], train_size=0.75); 

In [11]:
train.shape, test.shape

((45,), (15,))

### Tokenization + Vectorization
#### CountVectorizer

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
import re

In [13]:
stopwords_sp = stopwords.words('spanish')

In [14]:
vectorizer = CountVectorizer(stop_words = stopwords_sp, lowercase = True, strip_accents='unicode')
vectorizer.fit(list(re.sub(r'(\d|\$|\%|\+)', '', doc) for doc in corpus))

/home/guido/anaconda3/envs/dh/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:386: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['eramos', 'estabamos', 'estais', 'estan', 'estara', 'estaran', 'estaras', 'estare', 'estareis', 'estaria', 'estariais', 'estariamos', 'estarian', 'estarias', 'esteis', 'esten', 'estes', 'estuvieramos', 'estuviesemos', 'fueramos', 'fuesemos', 'habeis', 'habia', 'habiais', 'habiamos', 'habian', 'habias', 'habra', 'habran', 'habras', 'habre', 'habreis', 'habria', 'habriais', 'habriamos', 'habrian', 'habrias', 'hayais', 'hubieramos', 'hubiesemos', 'mas', 'mia', 'mias', 'mio', 'mios', 'seais', 'sera', 'seran', 'seras', 'sere', 'sereis', 'seria', 'seriais', 'seriamos', 'serian', 'serias', 'si', 'tambien', 'tendra', 'tendran', 'tendras', 'tendre', 'tendreis', 'tendria', 'tendriais', 'tendriamos', 'tendrian', 'tendrias', 'teneis', 'tengais', 'tenia', 'teniais', 'teniamos', 'tenian'

CountVectorizer(stop_words=['de', 'la', 'que', 'el', 'en', 'y', 'a', 'los',
                            'del', 'se', 'las', 'por', 'un', 'para', 'con',
                            'no', 'una', 'su', 'al', 'lo', 'como', 'más',
                            'pero', 'sus', 'le', 'ya', 'o', 'este', 'sí',
                            'porque', ...],
                strip_accents='unicode')

In [15]:
X_train = vectorizer.transform(train);

In [16]:
X_train

<45x2903 sparse matrix of type '<class 'numpy.int64'>'
	with 6235 stored elements in Compressed Sparse Row format>

In [17]:
X_train_matriz = X_train.todense()

In [18]:
X_test = vectorizer.transform(test);

In [19]:
X_test_matriz = X_train.todense()

#### Tf IDf Vectorizer

In [20]:
from sklearn.feature_extraction.text import TfidfTransformer

In [21]:
X_train_matriz_tfidf = TfidfTransformer().fit_transform(X_train_matriz);

In [22]:
X_test_matriz_tfidf = TfidfTransformer().fit_transform(X_test_matriz);

### Multinomial Naive Bayes + CountVectorizer

In [23]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [24]:
multi_nb = MultinomialNB()

multi_nb.fit(X_train, y_train.values)

MultinomialNB()

In [25]:
y_pred = multi_nb.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
accuracy_score(y_pred, y_test.values)

1.0

In [28]:
confusion_matrix(y_pred, y_test.values)

array([[ 5,  0],
       [ 0, 10]])

### Multinomial Naive Bayes + TfIDf

In [29]:
multi_nb_2 = MultinomialNB()

multi_nb_2.fit(X_train_matriz_tfidf, y_train.values)

MultinomialNB()

In [30]:
y_pred = multi_nb_2.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
accuracy_score(y_pred, y_test.values)

1.0

In [35]:
confusion_matrix(y_pred, y_test.values)

array([[ 5,  0],
       [ 0, 10]])

### Tokenization + Vectorization (Manual)

#### CountVectorizer with pre-built tokens

In [36]:
cv_tokens = pickle.load(open('tokens/topic_tokens_izq_new.pkl', 'rb'))

In [37]:
vectorizer.fit(cv_tokens.drop('topics', axis=1))

CountVectorizer(stop_words=['de', 'la', 'que', 'el', 'en', 'y', 'a', 'los',
                            'del', 'se', 'las', 'por', 'un', 'para', 'con',
                            'no', 'una', 'su', 'al', 'lo', 'como', 'más',
                            'pero', 'sus', 'le', 'ya', 'o', 'este', 'sí',
                            'porque', ...],
                strip_accents='unicode')

In [38]:
X_train_2 = vectorizer.transform(train)

In [39]:
X_train_matriz_2 = X_train_2.todense()

In [40]:
X_test_2 = vectorizer.transform(test)

In [41]:
X_test_matriz_2 = X_test_2.todense()

#### TF-IDF Vectorizer with pre-built tokens

In [42]:
X_train_matriz_tfidf_2 = TfidfTransformer().fit_transform(X_train_matriz_2);

In [43]:
X_test_matriz_tfidf_2 = TfidfTransformer().fit_transform(X_test_matriz_2);

### Multinomial Naive Bayes + CountVectorizer (updated tokens)

In [44]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [45]:
multi_nb = MultinomialNB()

multi_nb.fit(X_train_2, y_train.values)

MultinomialNB()

In [46]:
y_pred_2 = multi_nb.predict(X_test_2)

In [47]:
from sklearn.metrics import accuracy_score

In [48]:
accuracy_score(y_pred_2, y_test.values)

1.0

In [49]:
confusion_matrix(y_pred_2, y_test.values)

array([[ 5,  0],
       [ 0, 10]])

### Multinomial Naive Bayes + Tf IDf Vectorizer (updated tokens)

In [50]:
multi_nb_2 = MultinomialNB()

multi_nb_2.fit(X_train_matriz_tfidf_2, y_train.values)

MultinomialNB()

In [51]:
y_pred_2 = multi_nb_2.predict(X_test_matriz_tfidf_2)

In [52]:
from sklearn.metrics import accuracy_score

In [53]:
accuracy_score(y_pred_2, y_test.values)

1.0

In [54]:
confusion_matrix(y_pred_2, y_test.values)

array([[ 5,  0],
       [ 0, 10]])